### ISSUE TITLE
400 Bad Request at ping task

### ISSUE THREAD

**Issue by ozkantastan** [VahidN/DNTScheduler.Core#2]
/ is returns 200 but Ping task returns 400 :/

System.AggregateException
One or more errors occurred. (One or more errors occurred. (Response status code does not indicate success: 400 (Bad Request).))

DNTScheduler.Core.ScheduledTasksCoordinator in <.ctor>b__7_0
Assembly:DNTScheduler.Core
Version:1.1.0.0
Culture:neutral
PublicKeyToken:null

Name | .NET Core
Version | 3.0.2
raw_description | .NET Core 3.0.2

Name | Windows
Version | 10.0.14393
raw_description | Microsoft Windows 10.0.14393

**Comment by VahidN** [comment]
- This is the [ping task](https://github.com/VahidN/DNTScheduler.Core/blob/master/src/DNTScheduler.Core/ThisApplication.cs#L23). It just tries to fetch the `SiteRootUrl`. Make sure your site allows this task.
- Also if you don't want it, [just disable it](https://github.com/VahidN/DNTScheduler.Core/blob/master/src/DNTScheduler.TestWebApp/Startup.cs#L25).
